Aplicaciones/Emergencias/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add/',views.servicio_create_view, name='add'),
    path('lista_servicios/', views.servicio_list_view, name='lista_servicios'),
    path('prueba_catr/', views.prueba_catr, name='prueba_catr'),
    
    path('varios/', views.varios_list_view, name='varios'),
    path('ambulancia/', views.ambulancia_list_view, name='ambulancia'),
    path('incendios/', views.incendios_list_view, name='incendios'),
    path('ambulancia/<int:ambulancia_id>/reporte/', views.generar_reporte_ambulancia, name='generar_reporte_ambulancia'),
    path('varios/<int:varios_id>/reporte/', views.generar_reporte_servicios_varios, name='generar_reporte_varios'),
    path('incendios/<int:incendio_id>/reporte/', views.generar_reporte_incendios, name='generar_reporte_incendios'),
    path('editar_desactivar_varios/<int:pk>/', views.editar_desactivar_varios, name='editar_desactivar_varios'),
    path('pruebaservicios/', views.tabla_servicios, name='pruebaservicios'),
    path('vista_kilometraje/', views.vista_kilometraje, name='vista_kilometraje'),
    path('alertas/', views.alertas, name='alertas'),
    path('reporte_ambulancia/', views.reporte_ambulancia, name='reporte_ambulancia'),
    path('eliminar_servicio_varios/<int:servicio_id>/', views.eliminar_servicio_vario, name='eliminar_servicio_varios'),
    path('editar_servicio_varios/<int:servicio_id>/<int:vario_id>/', views.editar_servicio_vario, name='editar_servicio_varios'),
    path('eliminar_servicio_ambulancia/<int:servicio_id>/', views.eliminar_servicio_ambulancia, name='eliminar_servicio_ambulancia'),
    path('editar_servicio_ambulancia/<int:servicio_id>/<int:ambulancia_id>/', views.editar_servicio_ambulancia, name='editar_servicio_ambulancia'),
    path('eliminar_servicio_incendios/<int:servicio_id>/', views.eliminar_servicio_incendios, name='eliminar_servicio_incendios'),
    path('editar_servicio_incendios/<int:servicio_id>/<int:incendio_id>/', views.editar_servicio_incendios, name='editar_servicio_incendios'),
    
    path('crear/', views.crear_categoria, name='crear_categoria'),
    path('marcar_mantenimiento/<int:unidad_id>/', views.marcar_mantenimiento, name='marcar_mantenimiento'),

  
]

Sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views #importacion de librerias para login y logout de cada usuario en cada una de sus vistas

from django.conf.urls import handler404, handler500
from Aplicaciones.Administrativo.views import errores

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Aplicaciones.Administrativo.urls')),
    path('', include('Aplicaciones.user.urls')),
    path('', include('Aplicaciones.Publico.urls')),
    path('', include('Aplicaciones.emergenciasRecibidas.urls')),
    path('', include('Aplicaciones.lUsuarios.urls')),

    path('', include('Aplicaciones.Vehiculos.urls')),
    path('', include('Aplicaciones.EPP.urls')),
    path('', include('Aplicaciones.Herramientas.urls')),
    path('', include('Aplicaciones.Estadisticas.urls')),
    path('', include('Aplicaciones.Insumos.urls')),
    path('', include('Aplicaciones.Emergencias.urls')),
    path('', include('Aplicaciones.CV.urls')),
    
    
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout')
 
    
]
handler404 = errores

# Registrar el manejo de errores
handler500 = errores

Aplicaciones/Emergencias/models.py
# your_app/models.py

from django.db import models
from django.contrib.auth.models import User
from Aplicaciones.Vehiculos.models import Vehiculos
class Servicio(models.Model):
    SERVICIO_CHOICES = [
        ('1', 'Varios'),
        ('2', 'Ambulancia'),
        ('3', 'Incendios'),
    ]
    estacion = models.CharField(max_length=50)
    turno = models.CharField(max_length=50)
    direccion = models.CharField(max_length=255)
    telefonista =  models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        related_name='servicios_telefonista'
    )
    bombero_reporta = models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        related_name='servicios_reporta'
    )
    
    unidad = models.ForeignKey(Vehiculos, on_delete=models.CASCADE, related_name='servicios')  # Relación con Vehiculos
    piloto = models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        related_name='servicios_piloto'
    )
    salida_hora = models.DateTimeField()
    entrada_hora = models.DateTimeField()
    personal_asistente = models.CharField(max_length=100)
    observaciones = models.TextField()  # Cambiado a TextField
    km_entrada = models.DecimalField(max_digits=10, decimal_places=2)
    km_salida = models.DecimalField(max_digits=10, decimal_places=2)
    km_recorridos = models.FloatField()
    servicio = models.CharField(max_length=50, choices=SERVICIO_CHOICES)  # Añadido
    fecha_hora = models.DateTimeField(db_index=True)  # Añadido
    activo = models.BooleanField(default=True)  # Campo para desactivación lógica
    def __str__(self):
        return f"{self.servicio} - {self.fecha_hora}"


class Varios(models.Model):
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE, related_name='varios')

    fecha = models.DateField()
    servicio_de = models.CharField(max_length=100)
    jefe_servicio = models.CharField(max_length=100)
    servicio_autorizado_por = models.CharField(max_length=100)

    def __str__(self):
        return f"Varios - {self.servicio}"

class Categorias_emergencias(models.Model):
    id = models.CharField(primary_key=True, max_length=10)  # Sobrescribe el campo id
    nombre = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.nombre


class Ambulancia(models.Model):

    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE, related_name='ambulancia')
    codigo_emergencia = models.ForeignKey(Categorias_emergencias, on_delete=models.CASCADE, related_name='Categorias', null=True, blank=True)
    nombre_paciente = models.CharField(max_length=100)
    direccion_paciente = models.CharField(max_length=255)
    edad = models.PositiveIntegerField()
    sexo = models.CharField(max_length=10, choices=[
        ('F', 'Femenino'),
        ('M', 'Masculino'),
    ])
    traslado_a = models.CharField(max_length=100)  
    forma_aviso = models.CharField(max_length=100)
    hora_efectiva_servicio = models.TimeField()

    def __str__(self):
        return f"Ambulancia - {self.servicio}"


class Incendios(models.Model):
    PROPORCION_CHOICES = [
        ('Declarado', 'Declarado'),
        ('Medio', 'Medio'),
        ('Conato', 'Conato'),
    ]

    CLASE_FUEGO_CHOICES = [
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
    ]

    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE, related_name='incendios')
    servicio_incendio_inmueble = models.CharField(max_length=255)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    perdida = models.DecimalField(max_digits=10, decimal_places=2)
    proporcion = models.CharField(max_length=10, choices=PROPORCION_CHOICES)  # Cambiado a CharField
    clase_fuego = models.CharField(max_length=1, choices=CLASE_FUEGO_CHOICES)  # max_length ajustado
    hora_efectiva = models.DateTimeField()
    otras_unidades_asistentes_estacion = models.CharField(max_length=255)
    unidades_asistentes_otras_estaciones = models.CharField(max_length=255)
    unidades_policiacas = models.CharField(max_length=255)
    unidades_otras_instituciones_bomberiles = models.CharField(max_length=255)
    personal_asistente_otras_estaciones = models.CharField(max_length=255)
    jefe_servicio = models.CharField(max_length=100)
    fecha = models.DateField()

    def __str__(self):
        return f"Incendios - {self.servicio}"

Aplicaciones/Emergencias/forms.py
# your_app/forms.py

from django import forms
from .models import Servicio, Varios, Ambulancia, Incendios, Categorias_emergencias
from django.contrib.auth.models import User
class ServicioForm(forms.ModelForm):
    class Meta:
        model = Servicio
        fields = [
            'estacion', 'turno', 'direccion', 'telefonista', 'bombero_reporta',
            'unidad', 'piloto', 'salida_hora', 'entrada_hora',
            'personal_asistente', 'fecha_hora', 'km_entrada', 'km_salida',
            'km_recorridos', 'servicio', 'observaciones'
        ]
        widgets = {
            'fecha_hora': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'salida_hora': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'entrada_hora': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'servicio': forms.RadioSelect,  # Renderizar como botones de radio
        }
    def __init__(self, *args, **kwargs):
        super(ServicioForm, self).__init__(*args, **kwargs)
        # Filtrar para mostrar solo usuarios internos en los campos de usuario
        internal_users = User.objects.filter(profile__is_internal=True)
        
        self.fields['telefonista'].queryset = internal_users
        self.fields['bombero_reporta'].queryset = internal_users
        self.fields['piloto'].queryset = internal_users
        
class VariosForm(forms.ModelForm):
    servicio_de = forms.CharField(
        max_length=100, 
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Servicio De'})
    )
    jefe_servicio = forms.CharField(
        max_length=100, 
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Jefe de Servicio'})
    )
    servicio_autorizado_por = forms.CharField(
        max_length=100, 
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Servicio Autorizado Por'})
    )
    fecha = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    class Meta:
        model = Varios
        fields = ['fecha', 'servicio_de', 'jefe_servicio', 'servicio_autorizado_por']

class AmbulanciaForm(forms.ModelForm):
    codigo_emergencia = forms.ModelChoiceField(
        queryset=Categorias_emergencias.objects.all(),
        required=False,
        widget=forms.Select(attrs={'placeholder': 'Código de Emergencia'})
    )
    nombre_paciente = forms.CharField(
        max_length=100, 
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Nombre del Paciente'})
    )
    direccion_paciente = forms.CharField(
        max_length=255, 
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Dirección del Paciente'})
    )
    edad = forms.IntegerField(
        min_value=0, 
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Edad'})
    )
    sexo = forms.ChoiceField(
        choices=[
            ('F', 'Femenino'),
            ('M', 'Masculino'),
        ],
        required=False,
        widget=forms.Select()
    )
    traslado_a = forms.CharField(
        max_length=100, 
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Traslado A'})
    )
    forma_aviso = forms.CharField(
        max_length=100, 
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Forma de Aviso'})
    )
    hora_efectiva_servicio = forms.TimeField(
        required=False,
        widget=forms.TimeInput(attrs={'type': 'time'})
    )

    class Meta:
        model = Ambulancia
        fields = [
            'codigo_emergencia', 'nombre_paciente', 'direccion_paciente',
            'edad', 'sexo', 'traslado_a', 'forma_aviso', 'hora_efectiva_servicio'
        ]

class IncendiosForm(forms.ModelForm):
    servicio_incendio_inmueble = forms.CharField(
        max_length=255, 
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Servicio Incendio Inmueble'})
    )
    valor = forms.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Valor'})
    )
    perdida = forms.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Pérdida'})
    )
    proporcion = forms.ChoiceField(
        choices=Incendios.PROPORCION_CHOICES,
        required=False,
        widget=forms.Select(attrs={'placeholder': 'Proporción'})
    )
    clase_fuego = forms.ChoiceField(
        choices=Incendios.CLASE_FUEGO_CHOICES,
        required=False,
        widget=forms.Select(attrs={'placeholder': 'Clase de Fuego'})
    )
    hora_efectiva = forms.DateTimeField(
        required=False,
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'})
    )
    otras_unidades_asistentes_estacion = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Otras Unidades Asistentes en Estación'})
    )
    unidades_asistentes_otras_estaciones = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Unidades Asistentes en Otras Estaciones'})
    )
    unidades_policiacas = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Unidades Policiacas'})
    )
    unidades_otras_instituciones_bomberiles = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Unidades de Otras Instituciones Bomberiles'})
    )
    personal_asistente_otras_estaciones = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Personal Asistente en Otras Estaciones'})
    )
    fecha = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    class Meta:
        model = Incendios
        fields = [
            'servicio_incendio_inmueble', 'valor', 'perdida',
            'proporcion', 'clase_fuego', 'hora_efectiva',
            'otras_unidades_asistentes_estacion',
            'unidades_asistentes_otras_estaciones',
            'unidades_policiacas',
            'unidades_otras_instituciones_bomberiles',
            'personal_asistente_otras_estaciones',
            'fecha'
        ]
        
class CategoriasEmergenciasForm(forms.ModelForm):
    class Meta:
        model = Categorias_emergencias
        fields = ['id', 'nombre']

Aplicaciones/Emergencias/templates/add.html
{% extends "baseG.html" %} {% load static %} {% load crispy_forms_tags %}
{%block body %}

<div class="row justify-content-center">
  <div class="row justify-content-center">
    <div class="col-md-8 col-lg-6 form-container">
      <h1 class="text-center">Crear servicio</h1>
      <form method="post">
        {% csrf_token %}
        <fieldset>
          <legend>Información del Servicio</legend>
          {{ servicio_form|crispy }}
        </fieldset>

        <!-- Formulario Varios -->
        <fieldset id="varios-form" class="hidden-form">
          <legend>Información Varios</legend>
          {{ varios_form|crispy }}
        </fieldset>

        <!-- Formulario Ambulancia -->
        <fieldset id="ambulancia-form" class="hidden-form">
          <legend>Información Ambulancia</legend>
          {{ ambulancia_form|crispy }}
        </fieldset>

        <!-- Formulario Incendios -->
        <fieldset id="incendios-form" class="hidden-form">
          <legend>Información Incendios</legend>
          {{ incendios_form|crispy }}
        </fieldset>

        <button type="submit" class="bg-success text-light w-100">
          Guardar
        </button>
      </form>
    </div>
  </div>
</div>

<!-- Script JavaScript para manejar la visibilidad de los formularios adicionales -->
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const servicioRadios = document.querySelectorAll('input[name="servicio"]');
    const camposVarios = document.getElementById("varios-form");
    const camposAmbulancia = document.getElementById("ambulancia-form");
    const camposIncendios = document.getElementById("incendios-form");

    function toggleFields() {
      camposVarios.style.display = "none";
      camposAmbulancia.style.display = "none";
      camposIncendios.style.display = "none";

      const selectedService = document.querySelector(
        'input[name="servicio"]:checked'
      );
      if (selectedService) {
        if (selectedService.value === "1") {
          // Cambiado de "varios" a "1"
          camposVarios.style.display = "block";
        } else if (selectedService.value === "2") {
          camposAmbulancia.style.display = "block";
        } else if (selectedService.value === "3") {
          camposIncendios.style.display = "block";
        }
      }
    }

    servicioRadios.forEach((radio) => {
      radio.addEventListener("change", toggleFields);
    });

    // Ejecutar la función al cargar la página para manejar ediciones
    toggleFields();
  });
</script>
{% endblock %}

Aplicaciones/Emergencias/templates/alertas.html
{% extends "baseG.html" %} {% load static %} {% load crispy_forms_tags %}
{%block body %} {% if unidades_km %} {% for unidad, km in unidades_km.items %}
<div class="unidad-container">
  <p>
    Unidad: {{ unidad }} - Kilómetros recorridos desde último mantenimiento:
    {{km}}
  </p>

  {% if km >= 3000 %}
  <form method="POST" action="{% url 'marcar_mantenimiento' unidad.id %}">
    {% csrf_token %}
    <textarea
      name="notas"
      placeholder="Notas de mantenimiento (opcional)"
    ></textarea>
    <button type="submit" class="btn btn-primary">Marcar como Mantenido</button>
  </form>
  {% endif %}
</div>
{% endfor %} {% else %}
<h1>No hay unidades para mostrar</h1>
{% endif %} {% endblock %}

Aplicaciones/Emergencias/templates/crear.html
{% extends "baseG.html" %} {% load static %} {% load crispy_forms_tags %}
{%block body %}

<div class="row justify-content-center">
  <div class="row justify-content-center">
    <div class="col-md-8 col-lg-6 form-container">
      <h1>Crear Categoría de Emergencia</h1>
      <form method="post">
        {% csrf_token %} {{ form|crispy}}
        <button type="submit">Guardar</button>
      </form>
      <a href="{% url 'prueba_catr' %}">Volver al listado</a>
    </div>
  </div>
</div>

{% endblock %}

Aplicaciones/Emergencias/templates/editar.html
{% extends "baseG.html" %} {% load static %} {% load crispy_forms_tags %}
{%block body %}

<h1>Editar Categoría de Emergencia: {{ categoria.nombre }}</h1>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Actualizar</button>
</form>
<a href="{% url 'listar_categorias' %}">Volver al listado</a>

{% endblock %}

Aplicaciones/Emergencias/templates/varios.html
{% extends "baseG.html" %} {% load static %} {% block body %}
<div class="container mt-5">
  <h2 class="mb-4">Lista de Servicios Varios</h2>
  <a href="{% url 'add' %}" class="btn btn-primary">Volver</a>

  {% if messages %} {% for message in messages %}
  <div
    class="alert alert-{{ message.tags }} alert-dismissible fade show"
    role="alert"
  >
    {{ message }}
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Cerrar"
    ></button>
  </div>
  {% endfor %} {% endif %}

  <table id="myTable" class="table table-striped table-bordered border-success">
    <thead class="table-dark">
      <tr>
        <th class="header-cell w-5">Servicio:</th>
        <th class="header-cell w-5">Fecha y Hora:</th>
        <th class="header-cell w-5">Servicio de:</th>
        <th class="header-cell w-5">Jefe de Servicio</th>
        <th class="header-cell w-5">Autorizado Por:</th>
        <th class="header-cell w-5">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for varios in varios %}
      <tr>
        <td>{{ varios.servicio.get_servicio_display }}</td>
        <td>{{ varios.servicio.fecha_hora }}</td>
        <td>{{ varios.servicio_de }}</td>
        <td>{{ varios.jefe_servicio }}</td>
        <td>{{ varios.servicio_autorizado_por }}</td>
        <td>
          <button
            class="btn btn-warning"
            type="button"
            data-bs-toggle="modal"
            data-bs-target="#modalVarios{{ varios.id }}"
          >
            <i class="bi bi-eye"></i> Ver Detalles
          </button>
          <a
            href="{% url 'editar_servicio_varios' varios.servicio.id varios.id %}"
            class="btn btn-primary btn-sm"
          >
            <i class="bi bi-pencil-square"></i>
          </a>

          <!-- Formulario para Eliminar -->
          <!-- Formulario para Eliminar cada herramienta -->
          <form
            action="{% url 'eliminar_servicio_varios' varios.id %}"
            method="post"
            style="display: inline"
            id="deleteForm-{{ varios.id }}"
          >
            {% csrf_token %}
            <button
              type="button"
              class="btn btn-danger btn-sm"
              onclick="confirmDelete('{{ varios.id }}')"
            >
              <i class="bi bi-trash-fill"></i>
            </button>
          </form>
        </td>
      </tr>

      <!-- Modal for each Varios service -->
      <div
        class="modal fade"
        id="modalVarios{{ varios.id }}"
        tabindex="-1"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <form
              method="POST"
              action="{% url 'editar_desactivar_varios' varios.id %}"
            >
              {% csrf_token %}
              <div class="modal-header bg-warning">
                <h5 class="modal-title">Detalles del Servicio Varios</h5>
                <button
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Cerrar"
                ></button>
              </div>
              <div class="modal-body">
                <div class="row">
                  <!-- Información General -->
                  <div class="col-md-6">
                    <h6>Información General</h6>
                    <div class="mb-3">
                      <label class="form-label"
                        ><strong>Estación:</strong></label
                      >
                      <p>{{ varios.servicio.estacion }}</p>
                    </div>
                    <div class="mb-3">
                      <label class="form-label"><strong>Turno:</strong></label>
                      <p>{{ varios.servicio.turno }}</p>
                    </div>
                    <div class="mb-3">
                      <label class="form-label"
                        ><strong>Dirección:</strong></label
                      >
                      <p>{{ varios.servicio.direccion }}</p>
                    </div>
                    <div class="mb-3">
                      <label class="form-label"
                        ><strong>Telefonista:</strong></label
                      >
                      <p>{{ varios.servicio.telefonista }}</p>
                    </div>
                    <div class="mb-3">
                      <label class="form-label"
                        ><strong>Bombero reporta:</strong></label
                      >
                      <p>{{ varios.servicio.bombero_reporta }}</p>
                    </div>
                    <div class="mb-3">
                      <label class="form-label"><strong>Unidad:</strong></label>
                      <p>{{ varios.servicio.unidad }}</p>
                    </div>
                    <div class="mb-3">
                      <label class="form-label"><strong>Piloto:</strong></label>
                      <p>{{ varios.servicio.piloto }}</p>
                    </div>
                  </div>
                  <!-- Información Específica -->
                  <div class="col-md-6">
                    <h6>Detalles de Varios</h6>
                    <div class="mb-3">
                      <label class="form-label"><strong>Piloto:</strong></label>
                      <p>{{ varios.servicio.piloto }}</p>
                    </div>
                    <div class="mb-3">
                      <label class="form-label"
                        ><strong>Servicio de:</strong></label
                      >
                      <p>{{ varios.servicio_de }}</p>
                    </div>
                    <div class="mb-3">
                      <label class="form-label"
                        ><strong>Jefe de servicio:</strong></label
                      >
                      <p>{{ varios.jefe_servicio }}</p>
                    </div>
                    <div class="mb-3">
                      <label class="form-label"
                        ><strong>Servicio autorizado por:</strong></label
                      >
                      <p>{{ varios.servicio_autorizado_por }}</p>
                    </div>
                    <div class="mb-3">
                      <label class="form-label"
                        ><strong>Hora salida:</strong></label
                      >
                      <p>
                        {{ varios.servicio.salida_hora|date:'Y-m-d\\TH:i' }}
                      </p>
                    </div>
                    <div class="mb-3">
                      <label class="form-label"
                        ><strong>Hora entrada:</strong></label
                      >
                      <p>
                        {{ varios.servicio.entrada_hora|date:'Y-m-d\\TH:i' }}
                      </p>
                    </div>
                  </div>
                </div>
                <!-- Tercera columna para campos adicionales -->
                <div class="row mt-3">
                  <div class="col-12">
                    <h6>Información Adicional</h6>
                    <div class="row">
                      <div class="col-md-4">
                        <div class="mb-3">
                          <label class="form-label"
                            ><strong>Personal asistente:</strong></label
                          >
                          <p>{{ varios.servicio.personal_asistente }}</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <label class="form-label"
                            ><strong>Km entrada:</strong></label
                          >
                          <p>{{ varios.servicio.km_entrada }}</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <label class="form-label"
                            ><strong>Km salida:</strong></label
                          >
                          <p>{{ varios.servicio.km_salida }}</p>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-4">
                        <div class="mb-3">
                          <label class="form-label"
                            ><strong>Km recorridos:</strong></label
                          >
                          <p>{{ varios.servicio.km_recorridos }}</p>
                        </div>
                      </div>
                      <div class="col-md-8">
                        <div class="mb-3">
                          <label class="form-label"
                            ><strong>Observaciones:</strong></label
                          >
                          <p>{{ varios.servicio.observaciones }}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="modal-footer">
                <a
                  href="{% url 'generar_reporte_varios' varios.id %}"
                  class="btn btn-success"
                  >Descargar</a
                >
                <!-- <button
                  type="submit"
                  name="accion"
                  value="desactivar"
                  class="btn btn-danger"
                  onclick="return confirm('¿Está seguro de que desea desactivar este servicio?')"
                >
                  Desactivar
                </button>
                <button
                  type="submit"
                  name="accion"
                  value="editar"
                  class="btn btn-primary"
                >
                  Editar
                </button> -->
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-bs-dismiss="modal"
                >
                  Cerrar
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
      {% endfor %}
    </tbody>
  </table>
</div>
<script>
  function confirmDelete(codigo_her) {
    // Usamos SweetAlert para mostrar una alerta personalizada
    Swal.fire({
      title: "¿Estás seguro?",
      text: "No podrás revertir esta acción",
      icon: "warning",
      showCancelButton: true,
      confirmButtonColor: "#d33",
      cancelButtonColor: "#3085d6",
      confirmButtonText: "Sí, eliminarlo",
      cancelButtonText: "Cancelar",
    }).then((result) => {
      if (result.isConfirmed) {
        // Si el usuario confirma, enviamos el formulario específico por su ID
        document.getElementById(`deleteForm-${codigo_her}`).submit();
      }
    });
  }
</script>
{% endblock %}